name = "No-CSS Hugo"
license = "MIT"
licenselink = "https://github.com/automaciej/no-css/blob/master/LICENSE"
description = "No CSS, but with social meta tags."
homepage = "https://blizinski.pl/"
tags = ["Minimal", "Light", "Responsive", "No-CSS"]
features = ["social"]
min_version = "0.41.0"

[author]
  name = "Maciej Bliziński"
  homepage = "https://blizin.ski/"
